(function(g){var window=this;var sFa=function(a,b){return g.Pb(a,b)},$5=function(a,b,c){a.A.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.C)()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Fn(a.A,b,c)},tFa=function(a,b){var c=[];
g.Gk(b,function(d){try{var e=g.Eo.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Do(e)&&c.push(d)},a);
return c},uFa=function(a,b){var c=tFa(a,b);
(0,g.Db)(c,function(d){g.Eo.prototype.remove.call(this,d)},a)},vFa=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},wFa=function(a,b){g.ib(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},xFa=function(a,b){var c=b instanceof g.Dc?b:g.Jc(b,/^data:image\//i.test(b));
a.src=g.Ec(c)},d6=function(){},yFa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},zFa=function(a){if(a.Ud&&"function"==typeof a.Ud)return a.Ud();
if("string"===typeof a)return a.split("");if(g.Pa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Lb(a)},AFa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Pa(a)||"string"===typeof a)(0,g.Db)(a,b,void 0);else{if(a.gf&&"function"==typeof a.gf)var c=a.gf();else if(a.Ud&&"function"==typeof a.Ud)c=void 0;else if(g.Pa(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Mb(a);d=zFa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},BFa=function(a,b,c,d){var e=new g.tn(null,void 0);
a&&g.un(e,a);b&&g.vn(e,b);c&&g.wn(e,c);d&&(e.u=d);return e},e6=function(a,b){g.kp[a]=!0;
var c=g.ip();c&&c.publish.apply(c,arguments);g.kp[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.qn;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",CFa(this,a.capabilities||""),DFa(this,a.experiments||""))},CFa=function(a,b){a.capabilities.clear();
(0,g.Ie)(b.split(","),g.Ua(sFa,EFa)).forEach(function(c){a.capabilities.add(c)})},DFa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},FFa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},GFa=function(a){return new g6(a)},HFa=function(a){return Array.isArray(a)?(0,g.Nc)(a,GFa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+(0,g.Nc)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},IFa=function(a){return(0,g.Nc)(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.eb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.eb(a,function(c){return h6(c,b)})},JFa=function(){var a=(0,g.Dt)();
a&&uFa(a,a.o.Th(!0))},n6=function(){var a=g.Gt("yt-remote-connected-devices")||[];
g.zb(a);return a},KFa=function(a){if(g.jb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Nc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},LFa=function(a){g.Ft("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.Gt("yt-remote-device-id");a||(a=k6(),g.Ft("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.ib(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.ib(a,b);g.It()&&g.Cb(a,b);a=KFa(a);if(g.jb(a))try{g.Xq.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.Yq("remote_sid",a.join(","),-1)}catch(c){}},MFa=function(){return g.Gt("yt-remote-session-browser-channel")},NFa=function(){return g.Gt("yt-remote-local-screens")||[]},OFa=function(){g.Ft("yt-remote-lounge-token-expiration",!0,86400)},PFa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Nc)(NFa(),function(d){return d.loungeToken}),c=(0,g.Nc)(a,function(d){return d.loungeToken});
(0,g.Si)(c,function(d){return!g.ib(b,d)})&&OFa();
g.Ft("yt-remote-local-screens",a,31536E3)},QFa=function(a,b){g.Ft("yt-remote-session-browser-channel",a);
g.Ft("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.ib(c,d)||c.push(d);LFa(c);q6()},r6=function(a){a||(g.Ht("yt-remote-session-screen-id"),g.Ht("yt-remote-session-video-id"));
q6();a=n6();g.ob(a,p6());LFa(a)},RFa=function(){if(!s6){var a=g.Ko();
a&&(s6=new g.yo(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},SFa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},TFa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?UFa(a.shift(),function(){t6(a)}):u6()},VFa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},UFa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=TFa();
a&&a(!1,"No cast extension found")},XFa=function(){if(WFa){var a=2,b=TFa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;UFa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},YFa=function(){XFa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.y.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Id=b;this.C=(0,g.x)(this.CG,this);this.o=!1;this.u=0;this.A=this.La=null;this.B=[]},w6=function(a,b,c){g.y.call(this);
this.B=null!=c?a.bind(c):a;this.Id=b;this.A=null;this.o=!1;this.u=0;this.La=null},x6=function(a){a.La=g.ig(function(){a.La=null;
a.o&&!a.u&&(a.o=!1,x6(a))},a.Id);
var b=a.A;a.A=null;a.B.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return yFa(a)},z6=function(){},A6=function(){},ZFa=function(){},aGa=function(a){return(a=$Fa(a))?new ActiveXObject(a):new XMLHttpRequest},$Fa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},B6=function(a,b,c,d){this.o=a;
this.A=b;this.I=c;this.G=d||1;this.C=45E3;this.B=new g.x1(this);this.u=new g.hg;this.u.setInterval(250)},cGa=function(a,b,c){a.Vl=1;
a.Wh=a6(b.clone());a.ik=c;a.F=!0;bGa(a,null)},C6=function(a,b,c,d,e){a.Vl=1;
a.Wh=a6(b.clone());a.ik=null;a.F=c;e&&(a.rD=!1);bGa(a,d)},bGa=function(a,b){a.Ol=(0,g.C)();
D6(a);a.Pi=a.Wh.clone();b6(a.Pi,"t",a.G);a.wo=0;a.dd=a.o.Bt(a.o.ho()?b:null);0<a.ju&&(a.yr=new w6((0,g.x)(a.mE,a,a.dd),a.ju));a.B.ma(a.dd,"readystatechange",a.eO);var c=a.Aj?g.Wb(a.Aj):{};a.ik?(a.rs="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.dd.send(a.Pi,a.rs,a.ik,c)):(a.rs="GET",a.rD&&!g.we&&(c.Connection="close"),a.dd.send(a.Pi,a.rs,null,c));a.o.Vf(1)},fGa=function(a,b,c){for(var d=!0;!a.fj&&a.wo<c.length;){var e=dGa(a,c);
if(e==E6){4==b&&(a.ki=4,F6(15),d=!1);break}else if(e==eGa){a.ki=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.ki=1,F6(17),d=!1);a.eg=a.eg&&d;d||(H6(a),I6(a))},dGa=function(a,b){var c=a.wo,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if(isNaN(c))return eGa;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.wo=d+c;return e},hGa=function(a,b){a.Ol=(0,g.C)();
D6(a);var c=b?window.location.hostname:"";a.Pi=a.Wh.clone();$5(a.Pi,"DOMAIN",c);$5(a.Pi,"t",a.G);try{a.kg=new ActiveXObject("htmlfile")}catch(n){H6(a);a.ki=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in J6)h=J6[l];else if(l in gGa)h=J6[l]=gGa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
J6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.dd(g.hc("b/12014412"),d+"</body></html>");a.kg.open();a.kg.write(g.$c(c));a.kg.close();a.kg.parentWindow.m=(0,g.x)(a.tN,a);a.kg.parentWindow.d=(0,g.x)(a.yC,a,!0);a.kg.parentWindow.rpcClose=(0,g.x)(a.yC,a,!1);c=a.kg.createElement("DIV");a.kg.parentWindow.document.body.appendChild(c);d=g.Ic(a.Pi.toString());d=g.ld(g.Ec(d));d=g.dd(g.hc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ed(c,d);a.o.Vf(1)},D6=function(a){a.ix=(0,g.C)()+a.C;
iGa(a,a.C)},iGa=function(a,b){if(null!=a.cm)throw Error("WatchDog timer not null");
a.cm=K6((0,g.x)(a.DN,a),b)},L6=function(a){a.cm&&(g.v.clearTimeout(a.cm),a.cm=null)},I6=function(a){a.o.Fz()||a.fj||a.o.Up(a)},H6=function(a){L6(a);
g.Ue(a.yr);a.yr=null;a.u.stop();g.Qza(a.B);if(a.dd){var b=a.dd;a.dd=null;b.abort();b.dispose()}a.kg&&(a.kg=null)},G6=function(a,b){try{a.o.pC(a,b),a.o.Vf(4)}catch(c){}},kGa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;jGa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){kGa(a,b,c,d,f)},f)})}},jGa=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
xFa(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},lGa=function(a){this.o=a;
this.u=new z6},mGa=function(a){var b=N6(a.o,a.pm,"/mail/images/cleardot.gif");
a6(b);kGa(b.toString(),5E3,(0,g.x)(a.AF,a),3,2E3);a.Vf(1)},P6=function(a){var b=a.o.M;
if(null!=b)F6(5),b?(F6(11),O6(a.o,a,!1)):(F6(12),O6(a.o,a,!0));else if(a.ze=new B6(a,void 0,void 0,void 0),a.ze.Aj=a.hu,b=a.o,b=N6(b,b.ho()?a.Wm:null,a.iu),F6(5),!g.ue||g.Wd(10))b6(b,"TYPE","xmlhttp"),C6(a.ze,b,!1,a.Wm,!1);else{b6(b,"TYPE","html");var c=a.ze;a=!!a.Wm;c.Vl=3;c.Wh=a6(b.clone());hGa(c,a)}},Q6=function(a){g.xf.call(this);
this.headers=new g.qn;this.T=a||null;this.A=!1;this.U=this.o=null;this.ga=this.M="";this.F=0;this.B="";this.C=this.aa=this.I=this.Y=!1;this.G=0;this.N=null;this.fa="";this.R=this.Z=!1},nGa=function(a){return g.ue&&g.Vd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},oGa=function(a){return"content-type"==a.toLowerCase()},qGa=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;pGa(a);R6(a)},pGa=function(a){a.Y||(a.Y=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},sGa=function(a){if(a.A&&"undefined"!=typeof g.C1)if(a.U[1]&&4==S6(a)&&2==a.getStatus())T6(a,"Local request error detected and ignored");
else if(a.I&&4==S6(a))g.ig(a.lC,0,a);else if(a.dispatchEvent("readystatechange"),4==S6(a)){T6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.vd(1,String(a.M));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!rGa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<S6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";pGa(a)}}finally{R6(a)}}},R6=function(a,b){if(a.o){tGa(a);
var c=a.o,d=a.U[0]?g.Ka:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},tGa=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.N&&(g.v.clearTimeout(a.N),a.N=null)},S6=function(a){return a.o?a.o.readyState:0},U6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},T6=function(a,b){return b+" ["+a.ga+" "+a.M+" "+a.getStatus()+"]"},V6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new z6;this.I=a||null;this.M=null!=b?b:null;this.F=c||!1},xGa=function(a,b){this.o=a;
this.map=b;this.context=null},yGa=function(a){g.We.call(this,"statevent",a)},zGa=function(a,b,c,d){g.We.call(this,"timingevent",a);
this.size=b;this.Yn=d},AGa=function(a){g.We.call(this,"serverreachability",a)},DGa=function(a){BGa(a);
if(3==a.o){var b=a.En++,c=a.Dp.clone();$5(c,"SID",a.A);$5(c,"RID",b);$5(c,"TYPE","terminate");W6(a,c);b=new B6(a,a.A,b,void 0);b.Vl=2;b.Wh=a6(c.clone());xFa(new Image,b.Wh.toString());b.Ol=(0,g.C)();D6(b)}CGa(a)},EGa=function(a){a.aG(1,0);
a.Dp=N6(a,null,a.gu);X6(a)},BGa=function(a){a.Yh&&(a.Yh.abort(),a.Yh=null);
a.Ec&&(a.Ec.cancel(),a.Ec=null);a.Xg&&(g.v.clearTimeout(a.Xg),a.Xg=null);Y6(a);a.le&&(a.le.cancel(),a.le=null);a.ci&&(g.v.clearTimeout(a.ci),a.ci=null)},FGa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new xGa(a.dK++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.le||a.ci||(a.ci=K6((0,g.x)(a.xC,a),0),a.Pk=0)},HGa=function(a,b){if(1==a.o){if(!b){a.En=Math.floor(1E5*Math.random());
var c=a.En++,d=new B6(a,"",c,void 0);d.Aj=a.Wk;var e=Z6(a),f=a.Dp.clone();$5(f,"RID",c);$5(f,"CVER","1");W6(a,f);cGa(d,f,e);a.le=d;a.o=2}}else 3==a.o&&(b?GGa(a,b):0==a.u.length||a.le||GGa(a))},GGa=function(a,b){if(b)if(6<a.hj){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.En-1;var d=Z6(a)}else c=b.I,d=b.ik;else c=a.En++,d=Z6(a);var e=a.Dp.clone();$5(e,"SID",a.A);$5(e,"RID",c);$5(e,"AID",a.ol);W6(a,e);c=new B6(a,a.A,c,a.Pk+1);c.Aj=a.Wk;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.le=c;cGa(c,e,d)},W6=function(a,b){if(a.Fd){var c=a.Fd.dz();
c&&g.Fb(c,function(d,e){$5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.hj&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.hj?e:f-d;try{g.Fb(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},IGa=function(a){a.Ec||a.Xg||(a.G=1,a.Xg=K6((0,g.x)(a.wC,a),0),a.Dk=0)},$6=function(a){if(a.Ec||a.Xg||3<=a.Dk)return!1;
a.G++;a.Xg=K6((0,g.x)(a.wC,a),JGa(a,a.Dk));a.Dk++;return!0},O6=function(a,b,c){a.ls=c;
a.ug=b.oh;a.F||EGa(a)},Y6=function(a){null!=a.lj&&(g.v.clearTimeout(a.lj),a.lj=null)},JGa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Fd&&(c=null);var d=(0,g.x)(a.NO,a);c||(c=new g.tn("//www.google.com/images/cleardot.gif"),a6(c));jGa(c.toString(),1E4,d)}else F6(2);KGa(a,b)},KGa=function(a,b){a.o=0;
a.Fd&&a.Fd.vy(b);CGa(a);BGa(a)},CGa=function(a){a.o=0;
a.ug=-1;if(a.Fd)if(0==a.B.length&&0==a.u.length)a.Fd.jt();else{g.rb(a.B);var b=g.rb(a.u);a.B.length=0;a.u.length=0;a.Fd.jt(b)}},N6=function(a,b,c){var d=g.Bn(c);
if(""!=d.o)b&&g.vn(d,b+"."+d.o),g.wn(d,d.B);else{var e=window.location;d=BFa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Jm&&g.Fb(a.Jm,function(f,h){$5(d,h,f)});
$5(d,"VER",a.hj);W6(a,d);return d},K6=function(a,b){if(!g.Qa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},F6=function(a){b7.dispatchEvent(new yGa(b7,a))},LGa=function(){},MGa=function(){this.o=[];
this.u=[]},NGa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.y.call(this);
this.o=new g.F(this.mN,0,this);g.A(this,this.o);this.Id=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.x)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},d7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.N=a;this.F=b;this.A=new g.xo;this.u=new c7(this.sO,this);this.o=null;this.Qc=!1;this.C=null;this.M="";this.I=this.B=0;this.G=[];this.U=c;this.R=d},OGa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.ls,sessionId:a.o.A,arrayId:a.o.ol}},PGa=function(a,b){a.I=b||0;
a.u.stop();e7(a);a.o&&(3==a.o.o&&HGa(a.o),DGa(a.o));a.I=0},f7=function(a){return!!a.o&&3==a.o.o},e7=function(a){if(a.o){var b=a.R(),c=a.o.Wk||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.o.Wk=c}},QGa=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},g7=function(a){this.scheme="https";
this.port=this.domain="";this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.vd(4,a))||"";b&&(this.port=":"+b);this.domain=g.wd(a)||"";a=g.Tc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Bc(a,"10.0")&&(this.u=!1))},h7=function(a,b){var c=a.o;
a.u&&(c=a.scheme+"://"+a.domain+a.port+a.o);return g.Gd(c+b,{})},i7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ua(a.B,d,!0),onError:g.Ua(a.A,e),Qe:g.Ua(a.C,e)};c&&(a.Fb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Qq(b,a)},UGa=function(){var a=RGa;
SGa();j7.push(a);TGa(j7)},k7=function(a,b){SGa();
var c=j7,d=VGa(a,String(b));g.jb(c)?WGa(d):(TGa(c),(0,g.Db)(c,function(e){e(d)}))},SGa=function(){j7||(j7=g.Ja("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",j7,void 0))},WGa=function(a){var b=(l7+1)%50;
l7=b;m7[b]=a;n7||(n7=49==b)},TGa=function(a){var b=m7;
if(b[0]){var c=l7,d=n7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.Db)(a,function(f){f(e)})}while(d!=c);
m7=Array(50);l7=-1;n7=!1}},VGa=function(a,b){var c=((0,g.C)()-XGa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},o7=function(a){g.N.call(this);
this.F=a;this.screens=[]},YGa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},ZGa=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.Ie)(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=YGa(a,b[d])||c;return c},$Ga=function(a,b){var c=a.screens.length;
a.screens=(0,g.Ie)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},p7=function(a,b,c,d){g.N.call(this);
this.F=a;this.C=b;this.A=c;this.B=d;this.u=0;this.o=null;this.La=NaN},r7=function(a){o7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;q7(this);this.info("Initializing with "+j6(this.screens))},aHa=function(a){if(a.screens.length){var b=(0,g.Nc)(a.screens,function(d){return d.id}),c=h7(a.u,"/pairing/get_lounge_token_batch");
i7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.MG,a),(0,g.x)(a.LG,a))}},q7=function(a){var b=HFa(NFa());
b=(0,g.Ie)(b,function(c){return!c.uuid});
return ZGa(a,b)},s7=function(a,b){PFa((0,g.Nc)(a.screens,FFa));
b&&OFa()},u7=function(a,b){g.N.call(this);
this.F=b;var c=g.Gt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.ib(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;t7("Initialized with "+g.hl(this.o))},bHa=function(a,b,c){var d=h7(a.C,"/pairing/get_screen_availability");
i7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},v7=function(a,b){a:if(c6(b)!=c6(a.o))var c=!1;
else{c=g.Mb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(t7("Updated online screens: "+g.hl(a.o)),a.o=b,a.S("screenChange"));cHa(a)},w7=function(a){isNaN(a.A)||g.hp(a.A);
a.A=g.fp((0,g.x)(a.gw,a),0<a.B&&a.B<(0,g.C)()?2E4:1E4)},t7=function(a){k7("OnlineScreenService",a)},dHa=function(a){var b={};
(0,g.Db)(a.F(),function(c){c.token?b[c.token]=c.id:this.qc("Requesting availability of screen w/o lounge token.")});
return b},cHa=function(a){a=g.Mb(g.Gb(a.o,function(b){return b}));
g.zb(a);a.length?g.Ft("yt-remote-online-screen-ids",a.join(","),60):g.Ht("yt-remote-online-screen-ids")},x7=function(a){o7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};eHa(this)},gHa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.Je();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=y7(a,h);bHa(a.o,l,function(m){e(m?l:null)})}else c?fHa(a,c,(0,g.x)(function(m){var n=y7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));bHa(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},hHa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},fHa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Fb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Qq(h7(a.C,"/pairing/get_lounge_token_batch"),e)},iHa=function(a){a.screens=a.u.Je();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},eHa=function(a){z7(a);
a.u=new r7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.UG,a));iHa(a);a.A=HFa(g.Gt("yt-remote-automatic-screen-cache")||[]);z7(a);a.info("Initializing automatic screens: "+j6(a.A));a.o=new u7(a.C,(0,g.x)(a.Je,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Ft("yt-remote-automatic-screen-cache",(0,g.Nc)(a.A,FFa)));z7(a);a.B[b.uuid]=b.id;g.Ft("yt-remote-device-id-map",a.B,31536E3);return b},z7=function(a){a.B=g.Gt("yt-remote-device-id-map")||{}},A7=function(a,b,c){g.N.call(this);
this.U=c;this.M=a;this.o=b;this.I=null},B7=function(a,b){k7(a.U,b)},C7=function(a,b){A7.call(this,a,b,"CastSession");
this.u=null;this.A=0;this.C=(0,g.x)(this.uP,this);this.B=(0,g.x)(this.LN,this);this.A=g.fp((0,g.x)(function(){jHa(this,null)},this),12E4)},kHa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.hl(void 0));
var b={type:"getMdxSessionStatus"};a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ka,(0,g.x)(function(){B7(this,"Failed to send message: getMdxSessionStatus.")},a)):B7(a,"Sending yt message without session: "+g.hl(b))},jHa=function(a,b){g.hp(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.lr,a),d=(0,g.x)(a.Pe,a);a.yz(b,c,d,5)}}else a.Pe(Error("Waiting for session status timed out."))},D7=function(a,b,c){A7.call(this,a,b,"DialSession");
this.A=this.G=null;this.N="";this.T=c;this.B=null;this.F=g.Ka;this.C=NaN;this.R=(0,g.x)(this.xP,this);this.u=g.Ka},lHa=function(a){a.u=a.M.tE(a.N,a.o.label,a.o.friendlyName,(0,g.x)(function(b){this.u=g.Ka;
this.lr(b)},a),(0,g.x)(function(b){this.u=g.Ka;
this.Pe(b)},a))},mHa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}RFa()&&(b.env_useStageMdx=1);return g.Ed(b)},E7=function(a,b){A7.call(this,a,b,"ManualSession");
this.u=g.fp((0,g.x)(this.pl,this,null),150)},F7=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.I=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.AM,this)},nHa=function(a,b){return b?g.eb(a.A,function(c){return h6(b,c.label)},a):null},G7=function(a){k7("Controller",a)},RGa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},H7=function(a){return a.C||!!a.A.length||!!a.o},I7=function(a,b,c){b!=a.o&&(g.Ue(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.o):a.S("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.x)(a.uC,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.pl(null)):a.S("yt-remote-cast2-session-change",null))},oHa=function(a){var b=a.u.sE(),c=a.o&&a.o.o;
a=(0,g.Nc)(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=nHa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},uHa=function(a,b,c,d,e,f,h){pHa()?qHa(b,e,f,h)&&(K7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?rHa(a,c):(window.__onGCastApiAvailable=function(l,m){l?rHa(a,c):(L7("Failed to load cast API: "+m),M7(!1),K7(!1),g.Ht("yt-remote-cast-available"),g.Ht("yt-remote-cast-receiver"),sHa(),c(!1))},d?g.rp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?YFa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(XFa(),t6(tHa.map(VFa))))):J7("Cannot initialize because not running Chrome")},sHa=function(){J7("dispose");
var a=N7();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);vHa(!1);g.np(O7);O7.length=0},P7=function(){return!!g.Gt("yt-remote-cast-installed")},wHa=function(){var a=g.Gt("yt-remote-cast-receiver");
return a?a.friendlyName:null},xHa=function(){J7("clearCurrentReceiver");
g.Ht("yt-remote-cast-receiver")},yHa=function(){return P7()?N7()?N7().getCastSession():(L7("getCastSelector: Cast is not initialized."),null):(L7("getCastSelector: Cast API is not installed!"),null)},R7=function(){P7()?N7()?Q7()?(J7("Requesting cast selector."),N7().requestSession()):(J7("Wait for cast API to be ready to request the session."),O7.push(g.mp("yt-remote-cast2-api-ready",R7))):L7("requestCastSelector: Cast is not initialized."):L7("requestCastSelector: Cast API is not installed!")},S7=
function(a,b){Q7()?N7().setConnectedScreenStatus(a,b):L7("setConnectedScreenStatus called before ready.")},pHa=function(){var a=0<=g.Tc.search(/ (CrMo|Chrome|CriOS)\//);
return g.wx||a},zHa=function(a,b){N7().init(a,b)},qHa=function(a,b,c,d){var e=!1;
N7()||(a=new F7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ft("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){J7("onReceiverSelected: "+f.friendlyName);
g.Ft("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){J7("onReceiverResumed: "+f.friendlyName);
g.Ft("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){J7("onSessionChange: "+i6(f));
f||g.Ht("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
J7("cloudview.createSingleton_: "+e);return e},N7=function(){return g.Ja("yt.mdx.remote.cloudview.instance_")},rHa=function(a,b){M7(!0);
K7(!1);zHa(a,function(c){c?(vHa(!0),g.op("yt-remote-cast2-api-ready")):(L7("Failed to initialize cast API."),M7(!1),g.Ht("yt-remote-cast-available"),g.Ht("yt-remote-cast-receiver"),sHa());b(c)})},J7=function(a){k7("cloudview",a)},L7=function(a){k7("cloudview",a)},M7=function(a){J7("setCastInstalled_ "+a);
g.Ft("yt-remote-cast-installed",a)},Q7=function(){return!!g.Ja("yt.mdx.remote.cloudview.apiReady_")},vHa=function(a){J7("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},K7=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},T7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.vg=!1;this.M=this.I=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},U7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.vg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.C)();a.C=0;a.u=0;a.I=0;a.M=0;a.B=NaN;a.A=!1},V7=function(a){return a.tb()?((0,g.C)()-a.F)/1E3:0},W7=function(a,b){a.G=b;
a.F=(0,g.C)()},X7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Y7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&U7(a)},Z7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Xb(a.o);b.hasPrevious=a.vg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.I;b.loadedTime=a.M;b.liveIngestionTime=a.B;return b},a8=function(a,b){g.N.call(this);
this.o=0;this.B=a;this.F=[];this.C=new MGa;this.A=this.u=null;this.M=(0,g.x)(this.LK,this);this.G=(0,g.x)(this.In,this);this.I=(0,g.x)(this.KK,this);this.N=(0,g.x)(this.TK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.kx,this),AHa(this))):c=3;0!=c&&(b?this.kx(c):g.fp((0,g.x)(function(){this.kx(c)},this),0));
var d=yHa();d&&$7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},b8=function(a){return new T7(a.B.getPlayerContextData())},AHa=function(a){(0,g.Db)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Ua(this.wM,b),this))},a)},BHa=function(a){(0,g.Db)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},c8=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},e8=function(a,b,c){var d=b8(a);
W7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.B.sendMessage(b,c)},d8=function(a,b){BHa(a);
a.B.setPlayerContextData(Z7(b));AHa(a)},$7=function(a,b){a.A&&(a.A.removeUpdateListener(a.M),a.A.removeMediaListener(a.G),a.In(null));
a.A=b;a.A&&(k7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.M),a.A.addMediaListener(a.G),a.A.media.length&&a.In(a.A.media[0]))},CHa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=b8(a);b.contentId!=d.videoId&&k7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;W7(d,a.u.getEstimatedTime());d8(a,d)}else k7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.x)(function(d){this.qc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.qc("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.N.call(this);
this.C=NaN;this.R=!1;this.I=this.G=this.M=this.N=NaN;this.U=[];this.B=this.F=this.A=this.ib=this.o=null;this.Y=a;this.U.push(g.Cp(window,"beforeunload",(0,g.x)(this.FG,this)));this.u=[];this.ib=new T7;this.T=b.id;this.o=DHa(this,c);this.o.subscribe("handlerOpened",this.PK,this);this.o.subscribe("handlerClosed",this.MK,this);this.o.subscribe("handlerError",this.NK,this);this.o.subscribe("handlerMessage",this.OK,this);QGa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.ib.videoId;
g.It()&&g.Ft("yt-remote-session-video-id",d)},this)},i8=function(a){k7("conn",a)},DHa=function(a,b){return new d7(h7(a.Y,"/bc"),b,!1,function(){return a.pE()})},j8=function(a,b){a.S("proxyStateChange",b)},EHa=function(a){a.C=g.fp((0,g.x)(function(){i8("Connecting timeout");
this.Lk(1)},a),2E4)},k8=function(a){g.hp(a.C);
a.C=NaN},l8=function(a){g.hp(a.N);
a.N=NaN},FHa=function(a){m8(a);
a.M=g.fp((0,g.x)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.hp(a.M);
a.M=NaN},HHa=function(a,b){b&&(k8(a),l8(a));
b==(f7(a.o)&&isNaN(a.C))?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.wz()&&a.ib.reset(),j8(a,1),n8(a,"getNowPlaying"),GHa(a)):a.Lk(1)},IHa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ib.videoId&&(g.Sb(b.params)?a.ib.o=null:a.ib.o=b.params,a.S("remotePlayerChange"))},JHa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.ib.listId=b.params.listId||a.ib.listId;Y7(a.ib,c,d);a.S("remoteQueueChange")},LHa=function(a,b){b.params=b.params||{};
JHa(a,b);KHa(a,b);a.S("autoplayDismissed")},KHa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
W7(a.ib,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.ib.playerState&&(c=-1E3);a.ib.playerState=c;c=Number(b.params.loadedTime);a.ib.M=isNaN(c)?0:c;c=Number(b.params.duration);a.ib.I=isNaN(c)?0:c;c=a.ib;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.ib;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.ib.playerState?FHa(a):m8(a);a.S("remotePlayerChange")},MHa=function(a,b){if(-1E3!=
a.ib.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ib.playerState=c;c=parseInt(b.params.currentTime,10);W7(a.ib,isNaN(c)?0:c);a.S("remotePlayerChange")}},NHa=function(a,b){var c="true"==b.params.muted;
a.ib.volume=parseInt(b.params.volume,10);a.ib.muted=c;a.S("remotePlayerChange")},OHa=function(a,b){a.F=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},PHa=function(a,b){var c="true"==b.params.hasNext;
a.ib.vg="true"==b.params.hasPrevious;a.ib.hasNext=c;a.S("previousNextChange")},GHa=function(a){g.hp(a.I);
a.I=g.fp((0,g.x)(a.Lk,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.hl(c)):i8("Sending: action="+b);
a.o.sendMessage(b,c)},o8=function(a){o7.call(this,"ScreenServiceProxy");
this.Hd=a;this.o=[];this.o.push(this.Hd.$_s("screenChange",(0,g.x)(this.sP,this)));this.o.push(this.Hd.$_s("onlineScreenChange",(0,g.x)(this.aM,this)))},UHa=function(a,b){b=g.J("MDX_CONFIG")||b;
JFa();q6();p8||(p8=new g7(b?b.loungeApiHost:void 0),RFa()&&(p8.o="/api/loungedev"));q8||(q8=g.Ja("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",q8,void 0));QHa();var c=r8();if(!c){var d=new x7(p8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=r8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);uHa(a,d,function(m){m?s8()&&S7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){e6("yt-remote-receiver-availability-change")})},
e,f,h,l)}b&&!g.Ja("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),t8("Initializing: "+g.hl(b)),u8.push(g.mp("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),u8.push(g.mp("yt-remote-cast2-receiver-selected",function(){v8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),u8.push(g.mp("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),u8.push(g.mp("yt-remote-cast2-session-change",RHa)),u8.push(g.mp("yt-remote-connection-change",function(m){m?S7(s8(),"YouTube TV"):w8()||(S7(null,null),xHa())})),e=x8(),b.isAuto&&(e.id+="#dial"),g.Wo("desktop_enable_autoplay")&&(e.capabilities=["atp"]),e.name=b.device,e.app=b.app,(h=b.theme)&&(e.theme=h),t8(" -- with channel params: "+
g.hl(e)),SHa(e),c.start(),s8()||THa())},WHa=function(){var a=VHa();
P7()&&g.Gt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},VHa=function(){var a=r8().Hd.$_gos();
var b=y8();b&&z8()&&(l6(a,b)||a.push(b));return IFa(a)},A8=function(){var a=XHa();
!a&&P7()&&wHa()&&(a={key:"cast-selector-receiver",name:wHa()});return a},XHa=function(){var a=VHa(),b=y8();
b||(b=w8());return g.eb(a,function(c){return b&&h6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().Je();return m6(b,a)},RHa=function(a){t8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=y8();b&&b.id==a.id?S7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){Q7()?N7().stopSession():L7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){k7("remote",a)},r8=function(){if(!F8){var a=g.Ja("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.Ja("yt.mdx.remote.currentScreenId_")},YHa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},ZHa=function(){return g.Ja("yt.mdx.remote.connectData_")},v8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.Ja("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||YHa("");g.Ha("yt.mdx.remote.connection_",a,void 0);q8&&((0,g.Db)(q8,function(c){c(a)}),q8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},w8=function(){var a=g.It();
if(!a)return null;var b=r8();if(!b)return null;b=b.Je();return m6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{YHa(a.id);var c=new h8(p8,a,x8());c.connect(b,ZHa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},THa=function(){var a=w8();
a?(t8("Resume connection to: "+i6(a)),C8(a,0)):(r6(),xHa(),t8("Skipping connecting because no session screen found."))},QHa=function(){var a=x8();
if(g.Sb(a)){a=p6();var b=g.Gt("yt-remote-session-name")||"",c=g.Gt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.Ja("yt.mdx.remote.channelParams_")||{}},SHa=function(a){a?(g.Ft("yt-remote-session-app",a.app),g.Ft("yt-remote-session-name",a.name)):(g.Ht("yt-remote-session-app"),g.Ht("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.y.call(this);
var d=this;this.module=a;this.H=b;this.Za=c;this.events=new g.Is(this);this.M=this.events.L(this.H,"onVolumeChange",this.WB);this.B=!1;this.suggestion=null;this.C=new g.bH(64);this.o=new g.F(this.AD,500,this);this.u=new g.F(this.BD,1E3,this);this.G=new v6(this.XO,0,this);this.A={};this.I=new g.F(this.cE,1E3,this);this.F=new w6(this.seekTo,1E3,this);this.N=g.Ka;g.A(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.BL);this.events.L(b,"captionschanged",this.JK);this.events.L(b,"captionssettingschanged",
this.ED);this.events.L(b,"videoplayerreset",this.mr);this.events.L(b,"mdxautoplaycancel",function(){d.Za.Py()});
a=this.Za;a.ha();a.subscribe("proxyStateChange",this.oC,this);a.subscribe("remotePlayerChange",this.On,this);a.subscribe("remoteQueueChange",this.mr,this);a.subscribe("previousNextChange",this.kC,this);a.subscribe("nowAutoplaying",this.gC,this);a.subscribe("autoplayDismissed",this.GB,this);g.A(this,this.o);g.A(this,this.u);g.A(this,this.G);g.A(this,this.I);g.A(this,this.F);this.ED();this.mr();this.On()},$Ha=function(a){a.Wb(0);
a.o.stop();a.Oc(new g.bH(64))},K8=function(a,b){if(J8(a)&&!a.B){var c=null;
b&&(c={style:a.H.getSubtitlesUserSettings()},g.Zb(c,b));a.Za.qE(a.H.getVideoData(1).videoId,c);a.A=b8(a.Za).o}},L8=function(a,b){var c=a.H.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.H.getVideoData(1);a.Za.playVideo(c.videoId,b,d,e,c.playerParams,c.Le,vFa(c));a.Oc(new g.bH(1))},aIa=function(a,b){if(b){var c=a.H.getOption("captions","tracklist",{Wz:1});
c&&c.length?(a.H.setOption("captions","track",b),a.B=!1):(a.H.loadModule("captions"),a.B=!0)}else a.H.setOption("captions","track",{})},J8=function(a){return b8(a.Za).videoId===a.H.getVideoData(1).videoId},M8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",V:"Connecting to your TV on web using a code will be going away soon"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],V:"Learn more"},{D:"button",W:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],V:"OK"}]}]}]});this.o=new g.hP(this,250);this.learnMoreButton=
this.ca("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ca("ytp-mdx-manual-pairing-popup-ok");g.A(this,this.o);this.L(this.learnMoreButton,"click",this.u);this.L(this.okButton,"click",this.A)},N8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-popup-title",V:"You're signed out"},{D:"div",J:"ytp-mdx-popup-description",V:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",J:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Cancel"},{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
V:"Confirm"}]}]}]});this.o=new g.hP(this,250);this.cancelButton=this.ca("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ca("ytp-mdx-privacy-popup-confirm");g.A(this,this.o);this.L(this.cancelButton,"click",this.u);this.L(this.confirmButton,"click",this.A)},O8=function(a){g.U.call(this,{D:"div",
J:"ytp-remote",K:[{D:"div",J:"ytp-remote-display-status",K:[{D:"div",J:"ytp-remote-display-status-icon",K:[g.lN()]},{D:"div",J:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.api=a;this.o=new g.hP(this,250);g.A(this,this.o);this.L(a,"presentingplayerstatechange",this.u);bIa(this,g.jN(a))},bIa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.S(b,128)?g.NM("Error on $RECEIVER_NAME",c):b.tb()||g.S(b,4)?g.NM("Playing on $RECEIVER_NAME",c):g.NM("Connected to $RECEIVER_NAME",c);a.la("statustext",c);a.o.show()}else a.o.hide()},P8=function(a,b){g.$R.call(this,"Play on",0,a,b);
this.H=a;this.Oi={};this.L(a,"onMdxReceiversChange",this.B);this.L(a,"presentingplayerstatechange",this.B);this.B()},Q8=function(a){g.NO.call(this,a);
this.Qf={key:k6(),name:"This computer"};this.ng=null;this.subscriptions=[];this.Pv=this.Za=null;this.Oi=[this.Qf];this.ai=this.Qf;this.Sb=new g.bH(64);this.oA=0;this.kd=-1;this.rl=null;this.Pn=this.xq=!1;this.hk=this.Jl=null;if(!g.mz(this.player.O())){a=this.player;var b=g.$N(a);b&&(b=b.xj())&&(b=new P8(a,b),g.A(this,b));b=new O8(a);g.A(this,b);g.zO(a,b.element,4);this.Jl=new N8;g.A(this,this.Jl);g.zO(a,this.Jl.element,4);g.P(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.rl=new M8,g.A(this,this.rl),g.zO(a,this.rl.element,4));this.Pn=!!w8();this.xq=!!g.Gt("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.hk&&(a.player.removeEventListener("presentingplayerstatechange",a.hk),a.hk=null)},cIa=function(a,b,c){a.Sb=c;
a.player.S("presentingplayerstatechange",new g.kH(c,b))},dIa=function(a,b,c){var d=!1;
1===b?d=!a.Pn:2===b&&(d=!a.xq);d&&g.mH(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.ai.key)if(b.key===a.Qf.key)B8();
else{if(a.rl&&!a.xq&&b!==a.Qf&&"cast-selector-receiver"!==b.key&&g.vz(a.player.O()))eIa(a);else{var c;(c=!g.P(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.J("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.J("SESSION_INDEX")&&!g.J("LOGGED_IN")))||a.Pn||!a.Jl);(c?0:g.vz(a.player.O())||g.zz(a.player.O()))&&fIa(a)}a.ai=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.P(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ba(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Le,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=vFa(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.hl(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,Q7()?N7().setLaunchParams(c):L7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?e6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().Je(),(c=m6(c,b.key))&&C8(c,1))}},fIa=function(a){g.jN(a.player).tb()?a.player.pauseVideo():(a.hk=function(b){dIa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.hk));
a.Jl&&a.Jl.Xb();z8()||(G8=!0)},eIa=function(a){g.jN(a.player).tb()?a.player.pauseVideo():(a.hk=function(b){dIa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.hk));
a.rl&&a.rl.Xb();z8()||(G8=!0)},gGa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},J6={"'":"\\'"},gIa={},EFa={ZP:"atp",RS:"ska",CS:"que",QR:"mus",QS:"sus",YQ:"dsp",JS:"seq"},s6,o6="",WFa=SFa("loadCastFramework")||SFa("loadCastApplicationFramework"),tHa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Wa(v6,g.y);g.k=v6.prototype;g.k.BG=function(a){this.B=arguments;this.o=!1;this.La?this.A=(0,g.C)()+this.Id:this.La=g.ig(this.C,this.Id)};
g.k.stop=function(){this.La&&(g.v.clearTimeout(this.La),this.La=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.X=function(){this.stop();v6.wc.X.call(this)};
g.k.CG=function(){this.A?(this.La=g.ig(this.C,this.A-(0,g.C)()),this.A=null):(this.La=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.t(w6,g.y);g.k=w6.prototype;g.k.CA=function(a){this.A=arguments;this.La||this.u?this.o=!0:x6(this)};
g.k.stop=function(){this.La&&(g.v.clearTimeout(this.La),this.La=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.La||(this.o=!1,x6(this))};
g.k.X=function(){g.y.prototype.X.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};A6.prototype.o=null;A6.prototype.getOptions=function(){var a;(a=this.o)||(a={},$Fa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var T8;g.Wa(ZFa,A6);T8=new ZFa;g.k=B6.prototype;g.k.Aj=null;g.k.eg=!1;g.k.cm=null;g.k.ix=null;g.k.Ol=null;g.k.Vl=null;g.k.Wh=null;g.k.Pi=null;g.k.ik=null;g.k.dd=null;g.k.wo=0;g.k.kg=null;g.k.rs=null;g.k.ki=null;g.k.Xm=-1;g.k.rD=!0;g.k.fj=!1;g.k.ju=0;g.k.yr=null;var eGa={},E6={};g.k=B6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.eO=function(a){a=a.target;var b=this.yr;b&&3==S6(a)?b.CA():this.mE(a)};
g.k.mE=function(a){try{if(a==this.dd)a:{var b=S6(this.dd),c=this.dd.F,d=this.dd.getStatus();if(g.ue&&!g.Wd(10)||g.we&&!g.Vd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Rh&&!U6(this.dd))break a;this.fj||4!=b||7==c||(8==c||0>=d?this.o.Vf(3):this.o.Vf(2));L6(this);var e=this.dd.getStatus();this.Xm=e;var f=U6(this.dd);(this.eg=200==e)?(4==b&&H6(this),this.F?(fGa(this,b,f),g.Rh&&this.eg&&3==b&&(this.B.ma(this.u,"tick",this.YN),this.u.start())):G6(this,f),this.eg&&!this.fj&&(4==b?this.o.Up(this):(this.eg=
!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ki=3,F6(13)):(this.ki=0,F6(14)),H6(this),I6(this))}}catch(h){this.dd&&U6(this.dd)}finally{}};
g.k.YN=function(){var a=S6(this.dd),b=U6(this.dd);this.wo<b.length&&(L6(this),fGa(this,a,b),this.eg&&4!=a&&D6(this))};
g.k.tN=function(a){K6((0,g.x)(this.sN,this,a),0)};
g.k.sN=function(a){this.fj||(L6(this),G6(this,a),D6(this))};
g.k.yC=function(a){K6((0,g.x)(this.rN,this,a),0)};
g.k.rN=function(a){this.fj||(H6(this),this.eg=a,this.o.Up(this),this.o.Vf(4))};
g.k.cancel=function(){this.fj=!0;H6(this)};
g.k.DN=function(){this.cm=null;var a=(0,g.C)();0<=a-this.ix?(2!=this.Vl&&this.o.Vf(3),H6(this),this.ki=2,F6(18),I6(this)):iGa(this,this.ix-a)};
g.k.getLastError=function(){return this.ki};g.k=lGa.prototype;g.k.hu=null;g.k.ze=null;g.k.zr=!1;g.k.Gz=null;g.k.Bp=null;g.k.Lu=null;g.k.iu=null;g.k.jf=null;g.k.oh=-1;g.k.Wm=null;g.k.pm=null;g.k.connect=function(a){this.iu=a;a=N6(this.o,null,this.iu);F6(3);this.Gz=(0,g.C)();var b=this.o.I;null!=b?(this.Wm=b[0],(this.pm=b[1])?(this.jf=1,mGa(this)):(this.jf=2,P6(this))):(b6(a,"MODE","init"),this.ze=new B6(this,void 0,void 0,void 0),this.ze.Aj=this.hu,C6(this.ze,a,!1,null,!0),this.jf=0)};
g.k.AF=function(a){if(a)this.jf=2,P6(this);else{F6(4);var b=this.o;b.ug=b.Yh.oh;a7(b,9)}a&&this.Vf(2)};
g.k.Bt=function(a){return this.o.Bt(a)};
g.k.abort=function(){this.ze&&(this.ze.cancel(),this.ze=null);this.oh=-1};
g.k.Fz=function(){return!1};
g.k.pC=function(a,b){this.oh=a.Xm;if(0==this.jf)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.ug=this.oh;a7(c,2);return}this.Wm=c[0];this.pm=c[1]}else c=this.o,c.ug=this.oh,a7(c,2);else if(2==this.jf)if(this.zr)F6(7),this.Lu=(0,g.C)();else if("11111"==b){if(F6(6),this.zr=!0,this.Bp=(0,g.C)(),c=this.Bp-this.Gz,!g.ue||g.Wd(10)||500>c)this.oh=200,this.ze.cancel(),F6(12),O6(this.o,this,!0)}else F6(8),this.Bp=this.Lu=(0,g.C)(),this.zr=!1};
g.k.Up=function(){this.oh=this.ze.Xm;if(this.ze.eg)0==this.jf?this.pm?(this.jf=1,mGa(this)):(this.jf=2,P6(this)):2==this.jf&&((!g.ue||g.Wd(10)?!this.zr:200>this.Lu-this.Bp)?(F6(11),O6(this.o,this,!1)):(F6(12),O6(this.o,this,!0)));else{0==this.jf?F6(9):2==this.jf&&F6(10);var a=this.o;this.ze.getLastError();a.ug=this.oh;a7(a,2)}};
g.k.ho=function(){return this.o.ho()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Vf=function(a){this.o.Vf(a)};g.Wa(Q6,g.xf);var rGa=/^https?$/i,hIa=["POST","PUT"];g.k=Q6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.B="";this.F=0;this.ga=b;this.Y=!1;this.A=!0;this.o=this.T?aGa(this.T):aGa(T8);this.U=this.T?this.T.getOptions():T8.getOptions();this.o.onreadystatechange=(0,g.x)(this.lC,this);try{d6(T6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){d6(T6(this,"Error opening Xhr: "+f.message));qGa(this,f);return}a=
c||"";var e=this.headers.clone();d&&AFa(d,function(f,h){e.set(h,f)});
d=g.eb(e.gf(),oGa);c=g.v.FormData&&a instanceof g.v.FormData;!g.ib(hIa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.fa&&(this.o.responseType=this.fa);"withCredentials"in this.o&&this.o.withCredentials!==this.Z&&(this.o.withCredentials=this.Z);try{tGa(this),0<this.G&&(this.R=nGa(this.o),d6(T6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Hz,this)):this.N=g.ig(this.Hz,this.G,this)),d6(T6(this,"Sending request")),this.I=!0,this.o.send(a),this.I=!1}catch(f){d6(T6(this,"Send error: "+f.message)),qGa(this,f)}};
g.k.Hz=function(){"undefined"!=typeof g.C1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,T6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(T6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),R6(this))};
g.k.X=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),R6(this,!0));Q6.wc.X.call(this)};
g.k.lC=function(){this.ha()||(this.aa||this.I||this.C?sGa(this):this.zM())};
g.k.zM=function(){sGa(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<S6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=V6.prototype;g.k.Wk=null;g.k.Jm=null;g.k.le=null;g.k.Ec=null;g.k.gu=null;g.k.Dp=null;g.k.ly=null;g.k.Tp=null;g.k.En=0;g.k.dK=0;g.k.Fd=null;g.k.ci=null;g.k.Xg=null;g.k.lj=null;g.k.Yh=null;g.k.ls=null;g.k.ol=-1;g.k.nA=-1;g.k.ug=-1;g.k.Pk=0;g.k.Dk=0;g.k.hj=8;var b7=new g.xf;g.Wa(yGa,g.We);g.Wa(zGa,g.We);g.Wa(AGa,g.We);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){F6(0);this.gu=b;this.Jm=c||{};d&&void 0!==e&&(this.Jm.OSID=d,this.Jm.OAID=e);this.F?(K6((0,g.x)(this.Cy,this,a),100),EGa(this)):this.Cy(a)};
g.k.Cy=function(a){this.Yh=new lGa(this);this.Yh.hu=this.Wk;this.Yh.u=this.C;this.Yh.connect(a)};
g.k.Fz=function(){return 0==this.o};
g.k.xC=function(a){this.ci=null;HGa(this,a)};
g.k.wC=function(){this.Xg=null;this.Ec=new B6(this,this.A,"rpc",this.G);this.Ec.Aj=this.Wk;this.Ec.ju=0;var a=this.ly.clone();$5(a,"RID","rpc");$5(a,"SID",this.A);$5(a,"CI",this.ls?"0":"1");$5(a,"AID",this.ol);W6(this,a);if(!g.ue||g.Wd(10))$5(a,"TYPE","xmlhttp"),C6(this.Ec,a,!0,this.Tp,!1);else{$5(a,"TYPE","html");var b=this.Ec,c=!!this.Tp;b.Vl=3;b.Wh=a6(a.clone());hGa(b,c)}};
g.k.pC=function(a,b){if(0!=this.o&&(this.Ec==a||this.le==a))if(this.ug=a.Xm,this.le==a&&3==this.o)if(7<this.hj){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Xg){if(this.Ec)if(this.Ec.Ol+3E3<this.le.Ol)Y6(this),this.Ec.cancel(),this.Ec=null;else break a;$6(this);F6(19)}}else this.nA=c[1],0<this.nA-this.ol&&37500>c[2]&&this.ls&&0==this.Dk&&!this.lj&&(this.lj=K6((0,g.x)(this.FK,this),6E3));else a7(this,11)}else b!=gIa.xQ.o&&a7(this,11);else if(this.Ec==
a&&Y6(this),!g.pc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.ol=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Tp=e[2],e=e[3],null!=e?this.hj=e:this.hj=6,this.o=3,this.Fd&&this.Fd.yy(),this.ly=N6(this,this.ho()?this.Tp:null,this.gu),IGa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Fd&&this.Fd.wy(e),this.Dk=0)}}};
g.k.FK=function(){null!=this.lj&&(this.lj=null,this.Ec.cancel(),this.Ec=null,$6(this),F6(20))};
g.k.Up=function(a){if(this.Ec==a){Y6(this);this.Ec=null;var b=2}else if(this.le==a)this.le=null,b=1;else return;this.ug=a.Xm;if(0!=this.o)if(a.eg)1==b?(b=(0,g.C)()-a.Ol,b7.dispatchEvent(new zGa(b7,a.ik?a.ik.length:0,b,this.Pk)),X6(this),this.B.length=0):IGa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.ug)){if(d=1==b)this.le||this.ci||1==this.o||2<=this.Pk?d=!1:(this.ci=K6((0,g.x)(this.xC,this,a),JGa(this,this.Pk)),this.Pk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.aG=function(a){if(!g.ib(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.NO=function(a){a?F6(2):(F6(1),KGa(this,8))};
g.k.Bt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Q6;a.Z=!1;return a};
g.k.isActive=function(){return!!this.Fd&&this.Fd.isActive(this)};
g.k.Vf=function(a){b7.dispatchEvent(new AGa(b7,a))};
g.k.ho=function(){return!(!g.ue||g.Wd(10))};
g.k=LGa.prototype;g.k.yy=function(){};
g.k.wy=function(){};
g.k.vy=function(){};
g.k.jt=function(){};
g.k.dz=function(){return{}};
g.k.isActive=function(){return!0};g.k=MGa.prototype;g.k.isEmpty=function(){return g.jb(this.o)&&g.jb(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.ib(this.o,a)||g.ib(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.Vza)(b,a);0<=c?(g.lb(b,c),b=!0):b=!1;return b||g.ob(this.u,a)};
g.k.Ud=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Wa(c7,g.y);g.k=c7.prototype;g.k.mN=function(){this.Id=Math.min(3E5,2*this.Id);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Id+15E3*Math.random();this.o.jb(a);this.u=(0,g.C)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Id=5E3};g.Wa(d7,LGa);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.Gi=function(a){return this.A.Bj(a)};
g.k.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.k.dispose=function(){this.Qc||(this.Qc=!0,g.Ue(this.A),PGa(this),g.Ue(this.u),this.u=null,this.R=function(){return""})};
g.k.ha=function(){return this.Qc};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.M="";this.u.stop();this.C=a||null;this.B=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.U),e=this.o;e&&(e.Fd=null);d.Fd=this;this.o=d;e7(this);e?this.o.connect(a,b,this.F,e.A,e.ol):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Zb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):f7(this)&&(e7(this),FGa(this.o,c))};
g.k.yy=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)FGa(this.o,a[b])}this.S("handlerOpened")};
g.k.vy=function(a){var b=2==a&&401==this.o.ug;4==a||b||this.u.start();this.S("handlerError",a)};
g.k.jt=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.dz=function(){var a={v:2};this.M&&(a.gsessionid=this.M);0!=this.B&&(a.ui=""+this.B);0!=this.I&&(a.ui=""+this.I);this.C&&g.Zb(a,this.C);return a};
g.k.wy=function(a){"S"==a[0]?this.M=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),DGa(this.o)):this.S("handlerMessage",new NGa(a[0],a[1]))};
g.k.sO=function(){this.u.isActive();var a=this.o,b=0;a.Ec&&b++;a.le&&b++;0==b&&this.connect(this.C,this.B)};g7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
g7.prototype.C=function(a){a(Error("request timed out"))};var XGa=(0,g.C)(),j7=null,m7=Array(50),l7=-1,n7=!1;g.Wa(o7,g.N);o7.prototype.Je=function(){return this.screens};
o7.prototype.contains=function(a){return!!l6(this.screens,a)};
o7.prototype.get=function(a){return a?m6(this.screens,a):null};
o7.prototype.info=function(a){k7(this.F,a)};g.t(p7,g.N);g.k=p7.prototype;g.k.start=function(){!this.o&&isNaN(this.La)&&this.rE()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.La)||(g.hp(this.La),this.La=NaN)};
g.k.X=function(){this.stop();g.N.prototype.X.call(this)};
g.k.rE=function(){this.La=NaN;this.o=g.Qq(h7(this.F,"/pairing/get_screen"),{method:"POST",Fb:{pairing_code:this.C},timeout:5E3,onSuccess:(0,g.x)(this.qP,this),onError:(0,g.x)(this.pP,this),Qe:(0,g.x)(this.rP,this)})};
g.k.qP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.S("pairingComplete",new g6(c))};
g.k.pP=function(a){this.o=null;a.status&&404==a.status?this.u>=iIa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=iIa[this.u],this.La=g.fp((0,g.x)(this.rE,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.rP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var iIa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Wa(r7,o7);g.k=r7.prototype;g.k.start=function(){q7(this)&&this.S("screenChange");!g.Gt("yt-remote-lounge-token-expiration")&&aHa(this);g.hp(this.o);this.o=g.fp((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){q7(this);YGa(this,a);s7(this,!1);this.S("screenChange");b(a);a.token||aHa(this)};
g.k.remove=function(a,b){var c=q7(this);$Ga(this,a)&&(s7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.hs=function(a,b,c,d){var e=q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,s7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.X=function(){g.hp(this.o);r7.wc.X.call(this)};
g.k.MG=function(a){q7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}s7(this,!b);b&&k7(this.F,"Missed "+b+" lounge tokens.")};
g.k.LG=function(a){k7(this.F,"Requesting lounge tokens failed: "+a)};g.t(u7,g.N);g.k=u7.prototype;g.k.start=function(){var a=parseInt(g.Gt("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.C)()-144E5<a?0:a)?w7(this):(this.B=(0,g.C)()+3E5,g.Ft("yt-remote-fast-check-period",this.B),this.gw())};
g.k.isEmpty=function(){return g.Sb(this.o)};
g.k.update=function(){t7("Updating availability on schedule.");var a=this.F(),b=g.Gb(this.o,function(c,d){return c&&!!m6(a,d)},this);
v7(this,b)};
g.k.X=function(){g.hp(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.X.call(this)};
g.k.gw=function(){g.hp(this.A);this.A=NaN;this.u&&this.u.abort();var a=dHa(this);if(c6(a)){var b=h7(this.C,"/pairing/get_screen_availability");this.u=i7(this.C,b,{lounge_token:g.Mb(a).join(",")},(0,g.x)(this.WM,this,a),(0,g.x)(this.VM,this))}else v7(this,{}),w7(this)};
g.k.WM=function(a,b){this.u=null;var c=g.Mb(dHa(this));if(g.Ab(c,g.Mb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;v7(this,d);w7(this)}else this.qc("Changing Screen set during request."),this.gw()};
g.k.VM=function(a){this.qc("Screen availability failed: "+a);this.u=null;w7(this)};
g.k.qc=function(a){k7("OnlineScreenService",a)};g.Wa(x7,o7);g.k=x7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.hs=function(a,b,c,d){this.u.contains(a)?this.u.hs(a,b,c,d):(a="Updating name of unknown screen: "+a.name,k7(this.F,a),d(Error(a)))};
g.k.Je=function(a){return a?this.screens:g.qb(this.screens,(0,g.Ie)(this.A,function(b){return!this.contains(b)},this))};
g.k.sE=function(){return(0,g.Ie)(this.Je(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.tE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Ue(f);d(y7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Ue(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.tP=function(a,b,c,d){g.Qq(h7(this.C,"/pairing/get_screen"),{method:"POST",Fb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new g6(f.screen||{});if(!h.name||hHa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);hHa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(y7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Qe:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.X=function(){g.Ue(this.u);g.Ue(this.o);x7.wc.X.call(this)};
g.k.UG=function(){iHa(this);this.S("screenChange");this.o.update()};
x7.prototype.dispose=x7.prototype.dispose;g.Wa(A7,g.N);g.k=A7.prototype;g.k.getScreen=function(){return this.I};
g.k.lr=function(a){this.I=a;this.S("sessionScreen",this.I)};
g.k.Pe=function(a){this.ha()||(a&&B7(this,""+a),this.I=null,this.S("sessionScreen",null))};
g.k.info=function(a){k7(this.U,a)};
g.k.vE=function(){return null};
g.k.qw=function(a){var b=this.o;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){B7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.X=function(){this.qw("");A7.wc.X.call(this)};g.t(C7,A7);g.k=C7.prototype;g.k.pw=function(a){if(this.u){if(this.u==a)return;B7(this,"Overriding cast sesison with new session object");this.u.removeUpdateListener(this.C);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.u=a;this.u.addUpdateListener(this.C);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);kHa(this)};
g.k.pl=function(a){this.info("launchWithParams no-op for Cast: "+g.hl(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.x)(function(){this.Pe()},this),(0,g.x)(function(){this.Pe(Error("Failed to stop receiver app."))},this)):this.Pe(Error("Stopping cast device witout session."))};
g.k.qw=function(){};
g.k.X=function(){this.info("disposeInternal");g.hp(this.A);this.A=0;this.u&&(this.u.removeUpdateListener(this.C),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.u=null;A7.prototype.X.call(this)};
g.k.LN=function(a,b){if(!this.ha())if(b){var c=y6(b);if(g.Ra(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.hl(c));switch(d){case "mdxSessionStatus":jHa(this,c.screenId);break;default:B7(this,"Unknown youtube message: "+d)}}else B7(this,"Unable to parse message.")}else B7(this,"No data in message.")};
g.k.yz=function(a,b,c,d){gHa(this.M,this.o.label,a,this.o.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(B7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.fp((0,g.x)(this.yz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.vE=function(){return this.u};
g.k.uP=function(a){this.ha()||a||(B7(this,"Cast session died."),this.Pe())};g.t(D7,A7);g.k=D7.prototype;g.k.pw=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.k.pl=function(a){this.B=a;this.F()};
g.k.stop=function(){this.u();this.u=g.Ka;g.hp(this.C);this.A?this.A.stop((0,g.x)(this.Pe,this,null),(0,g.x)(this.Pe,this,"Failed to stop DIAL device.")):this.Pe()};
g.k.X=function(){this.u();this.u=g.Ka;g.hp(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;A7.prototype.X.call(this)};
g.k.xP=function(a){this.ha()||a||(B7(this,"DIAL session died."),this.u(),this.u=g.Ka,this.Pe())};
g.k.uu=function(a){this.N=k6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,mHa(this));a(b);lHa(this)}else this.F=(0,g.x)(function(){g.hp(this.C);this.F=g.Ka;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,mHa(this));a(c);lHa(this)},this),this.C=g.fp((0,g.x)(function(){this.F()},this),100)};
g.k.kH=function(a,b,c){gHa(this.M,this.G.receiver.label,a,this.o.friendlyName,(0,g.x)(function(d){d&&d.token?(this.lr(d),b(new chrome.cast.DialLaunchResponse(!1))):this.uu(b,c)},this),(0,g.x)(function(d){B7(this,"Failed to get DIAL screen: "+d);
this.uu(b,c)},this))};g.t(E7,A7);E7.prototype.stop=function(){this.Pe()};
E7.prototype.pw=function(){};
E7.prototype.pl=function(){g.hp(this.u);this.u=NaN;var a=m6(this.M.Je(),this.o.label);a?this.lr(a):this.Pe(Error("No such screen"))};
E7.prototype.X=function(){g.hp(this.u);this.u=NaN;A7.prototype.X.call(this)};g.t(F7,g.N);g.k=F7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.I||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.EM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.sC,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.YK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),UGa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.uE,this)),this.A=oHa(this),chrome.cast.setCustomReceivers(this.A,g.Ka,(0,g.x)(function(h){this.qc("Failed to set initial custom receivers: "+g.hl(h))},this)),this.S("yt-remote-cast2-availability-change",H7(this)),b(!0))},this),(0,g.x)(function(h){this.qc("Failed to initialize API: "+g.hl(h));
b(!1)},this))};
g.k.yO=function(a,b){G7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)G7("Unsetting old screen status: "+this.o.o.friendlyName),I7(this,null)}if(a&&b){if(!this.o){c=m6(this.u.Je(),a);if(!c){G7("setConnectedScreenStatus: Unknown screen.");return}var d=nHa(this,c);d||(G7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ka,(0,g.x)(function(e){this.qc("Failed to set initial custom receivers: "+g.hl(e))},this)));
G7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);I7(this,new E7(this.u,d),!0)}this.o.qw(b)}else G7("setConnectedScreenStatus: no screen.")};
g.k.zO=function(a){this.ha()?this.qc("Setting connection data on disposed cast v2"):this.o?this.o.pl(a):this.qc("Setting connection data without a session")};
g.k.wP=function(){this.ha()?this.qc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),I7(this,null)):G7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.sC,this),(0,g.x)(this.ZM,this))};
g.k.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.uE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=RGa,b=g.Ja("yt.mdx.remote.debug.handlers_");g.ob(b||[],a);g.Ue(this.o);g.N.prototype.X.call(this)};
g.k.qc=function(a){k7("Controller",a)};
g.k.uC=function(a,b){this.o==a&&(b||I7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.AM=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),G7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.o.label!=a.label)G7("onReceiverAction_: Stopping active receiver: "+this.o.o.friendlyName),this.o.stop();else{G7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:I7(this,
new E7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:I7(this,new D7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:I7(this,new C7(this.u,a));break;default:this.qc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.o.label==a.label?this.o.stop():this.qc("Stopping receiver w/o session: "+a.friendlyName)}else this.qc("onReceiverAction_ called without receiver.")};
g.k.YK=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.qc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.o:null;if(!c||c.label!=b.label)return this.qc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return G7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.qc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);I7(this,new D7(this.u,b,this.F))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.kH,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.uu,b))};
g.k.sC=function(a){if(!this.ha()){G7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)G7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),I7(this,new C7(this.u,b),!0);else{this.qc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.o,d=m6(this.u.Je(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(G7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ue(this.o),this.o=new C7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.uC,this,this.o)),this.o.pl(null));this.o.pw(a)}}};
g.k.vP=function(){return this.o?this.o.vE():null};
g.k.ZM=function(a){this.ha()||(this.qc("Failed to estabilish a session: "+g.hl(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&I7(this,null))};
g.k.EM=function(a){G7("Receiver availability updated: "+a);if(!this.ha()){var b=H7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;H7(this)!=b&&this.S("yt-remote-cast2-availability-change",H7(this))}};
g.k.uE=function(){this.ha()||(this.A=oHa(this),G7("Updating custom receivers: "+g.hl(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ka,(0,g.x)(function(){this.qc("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",H7(this)))};
F7.prototype.setLaunchParams=F7.prototype.zO;F7.prototype.setConnectedScreenStatus=F7.prototype.yO;F7.prototype.stopSession=F7.prototype.wP;F7.prototype.getCastSession=F7.prototype.vP;F7.prototype.requestSession=F7.prototype.requestSession;F7.prototype.init=F7.prototype.init;F7.prototype.dispose=F7.prototype.dispose;var O7=[];g.k=T7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";U7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.vg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.I=a.duration,this.M=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.tb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.I+V7(this):this.I};
g.k.clone=function(){return new T7(Z7(this))};g.t(a8,g.N);g.k=a8.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.Ka,g8(this,"play")):f8(this,"play"),e8(this,1,X7(b8(this))),this.S("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ka,g8(this,"pause")):f8(this,"pause"),e8(this,2,X7(b8(this))),this.S("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=b8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.tb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ka,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.S("remotePlayerChange")}else c8(this,g.Ua(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ka,g8(this,"stopVideo")):f8(this,"stopVideo");var a=b8(this);a.index=-1;a.videoId="";U7(a);d8(this,a);this.S("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=b8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){k7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.qc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){k7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.qc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Ua(this.setVolume,a,b))};
g.k.qE=function(a,b){if(1==this.o){var c=b8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.hl(b.style),g.Zb(d,c.o));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Ua(this.qE,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=b8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Ua(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=b8(this);c=c||0;var m={videoId:a,currentIndex:c};Y7(l,a,c);void 0!==b&&(W7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.hl(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.ur=function(a,b){if(1==this.o){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Ua(this.ur,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Ua(this.nextVideo,a,b))};
g.k.Py=function(){1==this.o?f8(this,"dismissAutoplay"):c8(this,this.Py)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.k.X=function(){BHa(this);this.B=null;this.C.clear();$7(this,null);g.N.prototype.X.call(this)};
g.k.kx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.jb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.wM=function(a,b){this.S(a,b)};
g.k.LK=function(a){if(!a)this.In(null),$7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=b8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.In=function(a){k7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.I);if(this.u=a)this.u.addUpdateListener(this.I),CHa(this),this.S("remotePlayerChange")};
g.k.KK=function(a){a?(CHa(this),this.S("remotePlayerChange")):this.In(null)};
g.k.Jw=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.TK=function(){var a=yHa();a&&$7(this,a)};
g.k.qc=function(a){k7("CP",a)};g.t(h8,g.N);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.ib.listId=c);this.ib.videoId=d;this.ib.index=h||0;this.ib.state=3;W7(this.ib,m);this.B="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.hl(l));this.o.connect({method:"setPlaylist",
params:g.hl(l)},a,MFa())}else i8("Connecting without params"),this.o.connect({},a,MFa());EHa(this)};
g.k.dispose=function(){this.ha()||(this.S("beforeDispose"),j8(this,3));g.N.prototype.dispose.call(this)};
g.k.X=function(){k8(this);m8(this);l8(this);g.hp(this.G);this.G=NaN;g.hp(this.I);this.I=NaN;this.A=null;g.Dp(this.U);this.U.length=0;this.o.dispose();g.N.prototype.X.call(this);this.B=this.F=this.u=this.ib=this.o=null};
g.k.FG=function(){this.Lk(2)};
g.k.PK=function(){i8("Channel opened");this.R&&(this.R=!1,l8(this),this.N=g.fp((0,g.x)(function(){i8("Timing out waiting for a screen.");this.Lk(1)},this),15E3));
QFa(OGa(this.o),this.T)};
g.k.MK=function(){i8("Channel closed");isNaN(this.C)?r6(!0):r6();this.dispose()};
g.k.NK=function(a){r6();isNaN(this.Sm())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,i8("Channel error: "+a+" with reconnection in "+this.Sm()+" ms"),j8(this,2))};
g.k.OK=function(a){a.params?i8("Received: action="+a.action+", params="+g.hl(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.u=(0,g.Nc)(a,function(c){return new f6(c)});
a=!!g.eb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
HHa(this,a);break;case "loungeScreenDisconnected":g.pb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
HHa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.eb(this.u,function(c){return b?c.id==b.id:!1})||wFa(this.u,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.pb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":JHa(this,a);break;case "nowPlaying":LHa(this,a);break;case "onStateChange":KHa(this,a);break;case "onAdStateChange":MHa(this,a);break;case "onVolumeChanged":NHa(this,a);break;case "onSubtitlesTrackChanged":IHa(this,a);break;case "nowAutoplaying":OHa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.S("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":PHa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.oO=function(){if(this.A){var a=this.A;this.A=null;this.ib.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.vG=function(){var a=3;this.ha()||(a=0,isNaN(this.Sm())?f7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Lk=function(a){i8("Disconnecting with "+a);k8(this);this.S("beforeDisconnect",a);1==a&&r6();PGa(this.o,a);this.dispose()};
g.k.tG=function(){var a=this.ib;this.A&&(a=this.ib.clone(),Y7(a,this.A,a.index));return Z7(a)};
g.k.AO=function(a){var b=new T7(a);b.videoId&&b.videoId!=this.ib.videoId&&(this.A=b.videoId,g.hp(this.G),this.G=g.fp((0,g.x)(this.oO,this),5E3));var c=[];this.ib.listId==b.listId&&this.ib.videoId==b.videoId&&this.ib.index==b.index||c.push("remoteQueueChange");this.ib.playerState==b.playerState&&this.ib.volume==b.volume&&this.ib.muted==b.muted&&X7(this.ib)==X7(b)&&g.hl(this.ib.o)==g.hl(b.o)||c.push("remotePlayerChange");this.ib.reset(a);(0,g.Db)(c,function(d){this.S(d)},this)};
g.k.wz=function(){var a=this.o.F.id,b=g.eb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Sm=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.C)():NaN};
g.k.iG=function(){return this.B||"UNSUPPORTED"};
g.k.jG=function(){return this.F||""};
g.k.oP=function(){if(!isNaN(this.Sm())){var a=this.o.u;g.Yn(a.o);a.start()}};
g.k.wO=function(a,b){n8(this,a,b);GHa(this)};
g.k.pE=function(){var a=g.Zq("SID","")||"",b=g.Zq("SAPISID","")||"";if(!a&&!b)return"";a=g.Ig(g.ng(a),2);b=g.Ig(g.ng(b),2);return g.Ig(g.ng(a+","+b),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.Gi;h8.prototype.getProxyState=h8.prototype.vG;h8.prototype.disconnect=h8.prototype.Lk;h8.prototype.getPlayerContextData=h8.prototype.tG;h8.prototype.setPlayerContextData=h8.prototype.AO;h8.prototype.getOtherConnectedRemoteId=h8.prototype.wz;h8.prototype.getReconnectTimeout=h8.prototype.Sm;h8.prototype.getAutoplayMode=h8.prototype.iG;h8.prototype.getAutoplayVideoId=h8.prototype.jG;h8.prototype.reconnect=h8.prototype.oP;
h8.prototype.sendMessage=h8.prototype.wO;h8.prototype.getXsrfToken=h8.prototype.pE;g.t(o8,o7);g.k=o8.prototype;g.k.Je=function(a){return this.Hd.$_gs(a)};
g.k.contains=function(a){return!!this.Hd.$_c(a)};
g.k.get=function(a){return this.Hd.$_g(a)};
g.k.start=function(){this.Hd.$_st()};
g.k.add=function(a,b,c){this.Hd.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Hd.$_r(a,b,c)};
g.k.hs=function(a,b,c,d){this.Hd.$_un(a,b,c,d)};
g.k.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.Hd.$_ubk(this.o[a]);this.o.length=0;this.Hd=null;o7.prototype.X.call(this)};
g.k.sP=function(){this.S("screenChange")};
g.k.aM=function(){this.S("onlineScreenChange")};
x7.prototype.$_st=x7.prototype.start;x7.prototype.$_gspc=x7.prototype.tP;x7.prototype.$_gsppc=x7.prototype.tE;x7.prototype.$_c=x7.prototype.contains;x7.prototype.$_g=x7.prototype.get;x7.prototype.$_a=x7.prototype.add;x7.prototype.$_un=x7.prototype.hs;x7.prototype.$_r=x7.prototype.remove;x7.prototype.$_gs=x7.prototype.Je;x7.prototype.$_gos=x7.prototype.sE;x7.prototype.$_s=x7.prototype.subscribe;x7.prototype.$_ubk=x7.prototype.Gi;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.t(I8,g.y);g.k=I8.prototype;g.k.X=function(){g.y.prototype.X.call(this);this.o.stop();this.u.stop();this.G.stop();this.N();var a=this.Za;a.unsubscribe("proxyStateChange",this.oC,this);a.unsubscribe("remotePlayerChange",this.On,this);a.unsubscribe("remoteQueueChange",this.mr,this);a.unsubscribe("previousNextChange",this.kC,this);a.unsubscribe("nowAutoplaying",this.gC,this);a.unsubscribe("autoplayDismissed",this.GB,this);this.Za=this.module=null};
g.k.SA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Za.o)if(J8(this)){if(!b8(this.Za).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":b8(this.Za).tb()?this.Za.pause():this.Za.play();break;case "control_play":this.Za.play();break;case "control_pause":this.Za.pause();break;case "control_seek":this.F.CA(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.H.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.JK=function(a){this.G.BG(a)};
g.k.XO=function(a){this.SA("control_subtitles_set_track",g.Sb(a)?null:a)};
g.k.ED=function(){var a=this.H.getOption("captions","track");g.Sb(a)||K8(this,a)};
g.k.Wb=function(a){this.module.Wb(a,this.H.getVideoData().lengthSeconds)};
g.k.WB=function(a){if(J8(this)){this.Za.unsubscribe("remotePlayerChange",this.On,this);var b=Math.round(a.volume);a=!!a.muted;var c=b8(this.Za);if(b!==c.volume||a!==c.muted)this.Za.setVolume(b,a),this.I.start();this.Za.subscribe("remotePlayerChange",this.On,this)}};
g.k.BL=function(){g.Sb(this.A)||aIa(this,this.A);this.B=!1};
g.k.oC=function(a,b){this.u.stop();2===b&&this.BD()};
g.k.On=function(){if(J8(this)){this.o.stop();var a=b8(this.Za);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.kd=1;break;case 1082:case 1083:this.module.kd=0;break;default:this.module.kd=-1}switch(a.playerState){case 1081:case 1:this.Oc(new g.bH(8));this.AD();break;case 1085:case 3:this.Oc(new g.bH(9));break;case 1083:case 0:this.Oc(new g.bH(2));this.F.stop();this.Wb(this.H.getVideoData().lengthSeconds);break;case 1084:this.Oc(new g.bH(4));break;case 2:this.Oc(new g.bH(4));
this.Wb(X7(a));break;case -1:this.Oc(new g.bH(64));break;case -1E3:this.Oc(new g.bH(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=b8(this.Za).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,aIa(this,a));a=b8(this.Za);-1===a.volume||Math.round(this.H.getVolume())===a.volume&&this.H.isMuted()===a.muted||this.I.isActive()||this.cE()}else $Ha(this)};
g.k.kC=function(){this.H.S("mdxpreviousnextchange")};
g.k.mr=function(){J8(this)||$Ha(this)};
g.k.gC=function(a){isNaN(a)||this.H.S("mdxnowautoplaying",a)};
g.k.GB=function(){this.H.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.Za.setAudioTrack(this.H.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===b8(this.Za).playerState?L8(this,a):b&&this.Za.seekTo(a)};
g.k.cE=function(){if(J8(this)){var a=b8(this.Za);this.events.rb(this.M);a.muted?this.H.mute():this.H.unMute();this.H.setVolume(a.volume);this.M=this.events.L(this.H,"onVolumeChange",this.WB)}};
g.k.AD=function(){this.o.stop();if(!this.Za.ha()){var a=b8(this.Za);a.tb()&&this.Oc(new g.bH(8));this.Wb(X7(a));this.o.start()}};
g.k.BD=function(){this.u.stop();this.o.stop();var a=this.Za.B.getReconnectTimeout();2==this.Za.o&&!isNaN(a)&&this.u.start()};
g.k.Oc=function(a){this.u.stop();var b=this.C;if(!g.gH(b,a)){var c=g.S(a,2);c!==g.S(this.C,2)&&g.uT(this.H.app,c);this.C=a;cIa(this.module,b,a)}};g.t(M8,g.U);M8.prototype.Xb=function(){this.o.show()};
M8.prototype.Ra=function(){this.o.hide()};
M8.prototype.u=function(){g.oP("https://support.google.com/youtube/answer/7640706")};
M8.prototype.A=function(){e6("mdx-manual-pairing-popup-ok");this.Ra()};g.t(N8,g.U);N8.prototype.Xb=function(){this.o.show()};
N8.prototype.Ra=function(){this.o.hide()};
N8.prototype.u=function(){e6("mdx-privacy-popup-cancel");this.Ra()};
N8.prototype.A=function(){e6("mdx-privacy-popup-confirm");this.Ra()};g.t(O8,g.U);O8.prototype.u=function(a){bIa(this,a.state)};g.t(P8,g.$R);P8.prototype.B=function(){var a=this.H.getOption("remote","receivers");a&&1<a.length&&!this.H.getOption("remote","quickCast")?(this.Oi=g.Eb(a,this.o,this),g.aS(this,(0,g.Nc)(a,this.o)),a=this.H.getOption("remote","currentReceiver"),this.Nb(this.o(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.o=function(a){return a.key};
P8.prototype.Tf=function(a){return"cast-selector-receiver"===a?"Cast...":this.Oi[a].name};
P8.prototype.td=function(a){g.$R.prototype.td.call(this,a);this.H.setOption("remote","currentReceiver",this.Oi[a]);this.Ia.Ra()};g.t(Q8,g.NO);g.k=Q8.prototype;
g.k.create=function(){var a=this.player.O(),b=g.cz(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.P(a.experiments,"mdx_load_cast_api_bootstrap_script")};UHa(b,a);this.subscriptions.push(g.mp("yt-remote-before-disconnect",this.HK,this));this.subscriptions.push(g.mp("yt-remote-connection-change",this.FM,this));this.subscriptions.push(g.mp("yt-remote-receiver-availability-change",this.mC,this));this.subscriptions.push(g.mp("yt-remote-auto-connect",this.DM,this));this.subscriptions.push(g.mp("yt-remote-receiver-resumed",
this.CM,this));this.subscriptions.push(g.mp("mdx-privacy-popup-confirm",this.cO,this));this.subscriptions.push(g.mp("mdx-privacy-popup-cancel",this.bO,this));this.subscriptions.push(g.mp("mdx-manual-pairing-popup-ok",this.BH,this));this.mC()};
g.k.load=function(){this.player.cancelPlayback();g.NO.prototype.load.call(this);this.ng=new I8(this,this.player,this.Za);var a=(a=ZHa())?a.currentTime:0;var b=E8()?new a8(z8(),void 0):null;0==a&&b&&(a=X7(b8(b)));0!==a&&this.Wb(a);cIa(this,this.Sb,this.Sb);g.AT(this.player.app,6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.ai=this.Qf;g.Ve(this.ng,this.Za);this.Za=this.ng=null;g.NO.prototype.unload.call(this);g.AT(this.player.app,5);R8(this)};
g.k.X=function(){g.np(this.subscriptions);g.NO.prototype.X.call(this)};
g.k.Ig=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.ng.SA.apply(this.ng,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.kd};
g.k.xG=function(){return this.loaded?this.ng.suggestion:null};
g.k.vg=function(){return this.Za?b8(this.Za).vg:!1};
g.k.hasNext=function(){return this.Za?b8(this.Za).hasNext:!1};
g.k.Wb=function(a,b){this.oA=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.oA};
g.k.getProgressState=function(){var a=b8(this.Za),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.jd():!a.isAdPlaying()&&this.player.jd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+V7(a):a.B,isAtLiveHead:1>=(a.A?a.u+V7(a):a.u)-this.getCurrentTime(),loaded:a.M,seekableEnd:a.A?a.u+V7(a):a.u,seekableStart:0<a.C?a.C+
V7(a):a.C}};
g.k.nextVideo=function(){this.Za&&this.Za.nextVideo()};
g.k.ur=function(){this.Za&&this.Za.ur()};
g.k.HK=function(a){1===a&&(this.Pv=this.Za?b8(this.Za):null)};
g.k.FM=function(){var a=E8()?new a8(z8(),void 0):null;if(a){var b=this.ai;this.loaded&&this.unload();this.Za=a;this.Pv=null;b.key!==this.Qf.key&&(this.ai=b,this.load())}else g.Ue(this.Za),this.Za=null,this.loaded&&(this.unload(),(a=this.Pv)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,X7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.mC=function(){this.Oi=[this.Qf].concat(WHa());var a=A8()||this.Qf;S8(this,a);this.player.oa("onMdxReceiversChange")};
g.k.DM=function(){var a=A8();S8(this,a)};
g.k.CM=function(){this.ai=A8()};
g.k.cO=function(){this.Pn=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.bO=function(){this.Pn=!1;R8(this);S8(this,this.Qf);this.ai=this.Qf;G8=!1;H8=null;this.player.playVideo()};
g.k.BH=function(){this.xq=!0;R8(this);g.Ft("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.fd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Oi;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?R7():S8(this,b)),this.loaded?this.ai:this.Qf;case "quickCast":return 2===this.Oi.length&&"cast-selector-receiver"===this.Oi[1].key?(b&&R7(),!0):!1}};
g.k.Jw=function(){this.Za.Jw()};
g.k.dg=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.YO.remote=Q8;})(_yt_player);
